/**
 * YouTube Transcript Extraction Types
 * 
 * Core types for the multi-layer transcript extraction system.
 * Used by both the Chrome extension and web application.
 */

// ============================================================================
// Core Segment Types
// ============================================================================

/**
 * A single transcript segment with timing and text data
 */
export interface TranscriptSegment {
  /** Start time in seconds */
  startTime: number;
  /** End time in seconds */
  endTime: number;
  /** Original text from caption source */
  rawText: string;
  /** Normalized/cleaned text */
  cleanedText: string;
}

// ============================================================================
// Metadata Types
// ============================================================================

/**
 * Metadata about the transcript source and quality
 */
export interface TranscriptMetadata {
  /** YouTube video ID */
  videoId: string;
  /** Human-readable language name (e.g., "English") */
  language: string;
  /** Language code (e.g., "en", "en-US") */
  languageCode: string;
  /** Whether the captions were auto-generated by YouTube */
  isAutoGenerated: boolean;
  /** Whether this is a translated track */
  isTranslated: boolean;
  /** Timestamp when the transcript was fetched */
  fetchedAt: number;
  /** Total duration covered by transcript in seconds */
  totalDuration: number;
  /** Number of segments */
  segmentCount: number;
}

// ============================================================================
// Status & Result Types
// ============================================================================

/**
 * Status of transcript extraction
 */
export enum TranscriptStatus {
  /** Transcript not yet requested */
  IDLE = 'idle',
  /** Extraction in progress */
  LOADING = 'loading',
  /** Transcript successfully extracted */
  READY = 'ready',
  /** Transcript partially extracted (some segments may be missing) */
  PARTIAL = 'partial',
  /** No transcript available for this video */
  UNAVAILABLE = 'unavailable',
  /** Extraction failed with an error */
  ERROR = 'error'
}

/**
 * Extraction layer that was used
 */
export enum ExtractionLayer {
  /** Caption endpoint via ytInitialPlayerResponse */
  CAPTION_ENDPOINT = 1,
  /** Player data inspection fallback */
  PLAYER_INSPECTION = 2,
  /** Auto-generated caption processing */
  AUTO_CAPTIONS = 3,
  /** DOM-based fallback (transcript panel) */
  DOM_FALLBACK = 4,
  /** No transcript available */
  UNAVAILABLE = 5
}

/**
 * Result of transcript extraction
 */
export interface TranscriptResult {
  /** Current status of extraction */
  status: TranscriptStatus;
  /** Extracted transcript segments */
  segments: TranscriptSegment[];
  /** Metadata about the transcript source */
  metadata: TranscriptMetadata | null;
  /** Error message if status is ERROR */
  error?: string;
  /** Which extraction layer succeeded */
  extractionLayer?: ExtractionLayer;
}

// ============================================================================
// Caption Track Types (from YouTube's internal API)
// ============================================================================

/**
 * Caption track information from YouTube player response
 */
export interface CaptionTrack {
  /** URL to fetch the caption file */
  baseUrl: string;
  /** Language code (e.g., "en") */
  languageCode: string;
  /** Human-readable track name */
  name: {
    simpleText?: string;
    runs?: Array<{ text: string }>;
  };
  /** Track kind - 'asr' for auto-generated, undefined for manual */
  kind?: string;
  /** Video ID this track belongs to */
  vssId?: string;
  /** Whether this track can be translated */
  isTranslatable?: boolean;
}

/**
 * Player captions data from ytInitialPlayerResponse
 */
export interface PlayerCaptionsData {
  /** Available caption tracks */
  captionTracks?: CaptionTrack[];
  /** Audio tracks (for language detection) */
  audioTracks?: Array<{
    captionTrackIndices?: number[];
  }>;
  /** Translation languages available */
  translationLanguages?: Array<{
    languageCode: string;
    languageName: { simpleText: string };
  }>;
}

// ============================================================================
// Message Types (for Chrome extension communication)
// ============================================================================

/**
 * Message types for transcript-related communication
 */
export type TranscriptMessageType =
  | 'GET_TRANSCRIPT'
  | 'TRANSCRIPT_READY'
  | 'TRANSCRIPT_ERROR'
  | 'GET_TRANSCRIPT_STATUS'
  | 'CLEAR_TRANSCRIPT_CACHE';

/**
 * Message payload for transcript operations
 */
export interface TranscriptMessage {
  type: TranscriptMessageType;
  payload?: {
    videoId?: string;
    status?: TranscriptStatus;
    result?: TranscriptResult;
    error?: string;
  };
}
